### ISSUE TITLE
Wygląd Strony

### ISSUE THREAD

**Issue by makoteq** [Mensix/spis-sekcji-next#1]
Myślę że wygląd strony można poprawić upraszczając go, Na dole zamieszczam luźny koncept (środek strony nie w skali więc proszę się tym nie kierować). 
![Desktop - 1](https://user-images.githubusercontent.com/42750440/94736065-f1520380-036b-11eb-8744-5fe572567471.png)

**Comment by makoteq** [comment]
Jak jest coś innego do zrobienia to chętnie się tym zajmę

**Comment by Mensix** [comment]
Całkiem ciekawy koncept, lecz zmiany wyglądu strony raczej nie przewidujemy :)

Natomiast w najbliższej przyszłości będzie trzeba kod przenieść na Nuxt 3 oraz Quasar 2 (UI framework na którym oparty jest spis, widziałem roboczego brancha pod Vue 3, trochę zmian jest) oraz lekko uporządkować kod. Jeśli chcesz, to oczywiście możesz się tego zadania podjąć.
